[sel NEW_TV_SEL]
[f 0 5 -258][f 2 1]Watch the Midnight Channel[e]
[f 0 5 -258][f 2 1]Watch the fortune telling program[e]
[f 0 5 -258][f 2 1]Watch the weather forecast[e]
[f 0 5 -258][f 2 1]Watch the shopping program[e]
[f 0 5 -258][f 2 1]Quit[e]

[msg FORTUNE_TELLER_HELP]
[f 0 5 -258][f 2 1]By watching the fortune telling program you will[n]
gain a deeper understanding of the growth of[n]
your social stats.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Whilst watching the program you can adjust the TV
[n]to change how precise the readings will be.[n][f 1 1][e]

[sel FORTUNE_SEL]
[f 0 5 -258][f 2 1]Yes[e]
[f 0 5 -258][f 2 1]No[e]
[f 0 5 -258][f 2 1]Adjust TV[e]

[msg FORTUNE_QUESTION_1 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]I sense a new viewer joining the show
[n]from a very small town.[n][f 1 1][e]

[msg FORTUNE_QUESTION_2 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]Tell me, new viewer, do you 
[n]believe in fortune telling?[n][f 1 1][e]

[msg FORTUNE_MAX_COURAGE [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]The [f 0 1 1]Courage[f 0 1 0] in your soul is truly remarkable. 
[n]Is such a trait a given for you, 
[n]or a result of challenging hardships?[n][f 1 1][e]
[f 0 5 -258][f 2 1]Do remember that you must back away sometimes, 
[n]lest your bravery become naivete.[n][f 1 1][e]

[msg FORTUNE_MAX_KNOWLEDGE [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]My, so smart, yet so young! 
[n]Do be careful, young man, 
[n]for [f 0 1 1]Knowledge[f 0 1 0] is not wisdom.[n][f 1 1][e]

[msg FORTUNE_MAX_DILIGENCE [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]Persistent, are you? You chase your dreams, 
[n]even, or especially, when they push back.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Such [f 0 1 1]Diligence[f 0 1 0] is 
[n]rarely found in the souls of today's youths.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Youths should know their limits, however, 
[n]and you are surpassing yours... perhaps
[n]to the point where it is unsafe.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Careful, now. Careful.[n][f 1 1][e]

[msg FORTUNE_MAX_UNDERSTANDING [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]Now, I can see that you have faced many, 
[n]many challenges, perhaps even in a short span of time.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Yet, throughout this, you have not 
[n]hardened your heart...in fact, 
[n]quite the opposite.[n][f 1 1][e]
[f 0 5 -258][f 2 1]I applaud you, not many would
[n]hold any [f 0 1 1]Understanding[f 0 1 0] in their hearts 
[n]after living through extraordinary pain.[n][f 1 1][e]

[msg FORTUNE_MAX_EXPRESSION [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]We have all heard "honesty is the best policy," no? 
[n]New viewer, be wary of this. [n][f 1 1][e]
[f 0 5 -258][f 2 1]For while you may be a master 
[n]of honest [f 0 1 1]Expression[f 0 1 0], the truth can 
[n]be a danger. Tread carefully, now.[n][f 1 1][e]

[msg FORTUNE_COURAGE_POINTS_NEEDED]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] points needed to level up [f 0 1 1]Courage[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_KNOWLEDGE_POINTS_NEEDED]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] points needed to level up [f 0 1 1]Knowledge[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_DILIGENCE_POINTS_NEEDED]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] points needed to level up [f 0 1 1]Diligence[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_UNDERSTANDING_POINTS_NEEDED]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] points needed to level up [f 0 1 1]Understanding[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_EXPRESSION_POINTS_NEEDED]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] points needed to level up [f 0 1 1]Expression[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_COURAGE_POINTS_NEEDED_1]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] point needed to level up [f 0 1 1]Courage[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_KNOWLEDGE_POINTS_NEEDED_1]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] point needed to level up [f 0 1 1]Knowledge[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_DILIGENCE_POINTS_NEEDED_1]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] point needed to level up [f 0 1 1]Diligence[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_UNDERSTANDING_POINTS_NEEDED_1]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] point needed to level up [f 0 1 1]Understanding[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_EXPRESSION_POINTS_NEEDED_1]
[f 0 5 -258][f 2 1]>You see something flash on screen for a moment.
[n]"[f 2 4 0] point needed to level up [f 0 1 1]Expression[f 0 1 0]"[n][f 1 1][e]

[msg FORTUNE_END_SPECIFIC]
[f 0 5 -258][f 2 1]>...[f 1 1][e]
[f 0 5 -258][f 2 1]>... did anybody else see that?
[n]How odd... 
[n]and specific...[f 1 1][e]
[f 0 5 -258][f 2 1]>You turn off the TV.[f 1 1][e]

[msg FORTUNE_END]
[f 0 5 -258][f 2 1]>...[f 1 1][e]
[f 0 5 -258][f 2 1]>... did anybody else see that?
[n]How odd...[f 1 1][e]
[f 0 5 -258][f 2 1]>You turn off the TV.[f 1 1][e]

[msg FORTUNE_COURAGE_PROGRESS_1 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have a long way to go
[n]before you become more [f 0 1 1]Courageous[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_KNOWLEDGE_PROGRESS_1 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have a long way to go
[n]before you become more [f 0 1 1]Knowledgeable[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_DILIGENCE_PROGRESS_1 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have a long way to go
[n]before you become more [f 0 1 1]Diligent[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_UNDERSTANDING_PROGRESS_1 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have a long way to go
[n]before you become more [f 0 1 1]Understanding[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_EXPRESSION_PROGRESS_1 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have a long way to go
[n]before you become more [f 0 1 1]Expressive[f 0 1 0].[n][f 1 1][e]


[msg FORTUNE_COURAGE_PROGRESS_2 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made some progress, 
[n]however there is still much to learn
[n]before you become more [f 0 1 1]Courageous[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_KNOWLEDGE_PROGRESS_2 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made some progress, 
[n]however there is still much to learn
[n]before you become more [f 0 1 1]Knowledgeable[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_DILIGENCE_PROGRESS_2 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made some progress, 
[n]however there is still much to learn
[n]before you become more [f 0 1 1]Diligent[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_UNDERSTANDING_PROGRESS_2 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made some progress, 
[n]however there is still much to learn
[n]before you become more [f 0 1 1]Understanding[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_EXPRESSION_PROGRESS_2 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made some progress, 
[n]however there is still much to learn
[n]before you become more [f 0 1 1]Expressive[f 0 1 0].[n][f 1 1][e]


[msg FORTUNE_COURAGE_PROGRESS_3 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made much progress. However, 
[n]there is still more for you to learn 
[n]before you become more [f 0 1 1]Courageous[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_KNOWLEDGE_PROGRESS_3 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made much progress. However, 
[n]there is still more for you to learn 
[n]before you become more [f 0 1 1]Knowledgeable[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_DILIGENCE_PROGRESS_3 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made much progress. However, 
[n]there is still more for you to learn 
[n]before you become more [f 0 1 1]Diligent[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_UNDERSTANDING_PROGRESS_3 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made much progress. However, 
[n]there is still more for you to learn 
[n]before you become more [f 0 1 1]Understanding[f 0 1 0].[n][f 1 1][e]

[msg FORTUNE_EXPRESSION_PROGRESS_3 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You have made much progress. However, 
[n]there is still more for you to learn 
[n]before you become more [f 0 1 1]Expressive[f 0 1 0].[n][f 1 1][e]


[msg FORTUNE_COURAGE_PROGRESS_4 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You are on the cusp of becoming more
[n][f 0 1 1]Courageous[f 0 1 0]. Don't slack off now.[n][f 1 1][e]

[msg FORTUNE_KNOWLEDGE_PROGRESS_4 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You are on the cusp of becoming more
[n][f 0 1 1]Knowledgeable[f 0 1 0]. Don't slack off now.[n][f 1 1][e]

[msg FORTUNE_DILIGENCE_PROGRESS_4 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You are on the cusp of becoming more
[n][f 0 1 1]Diligent[f 0 1 0]. Don't slack off now.[n][f 1 1][e]

[msg FORTUNE_UNDERSTANDING_PROGRESS_4 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You are on the cusp of becoming more
[n][f 0 1 1]Understanding[f 0 1 0]. Don't slack off now.[n][f 1 1][e]

[msg FORTUNE_EXPRESSION_PROGRESS_4 [Mysterious Fortune Teller]]
[f 0 5 -258][f 2 1]You are on the cusp of becoming more
[n][f 0 1 1]Expressive[f 0 1 0]. Don't slack off now.[n][f 1 1][e]


[msg ADJUST_PRECISE]
[f 0 5 -258][f 2 1]The picture appears clearer now.
[n]You should be able to get a 
[n]more precise fortune.[f 1 1][e]

[msg ADJUST_FUZZY]
[f 0 5 -258][f 2 1]The picture has become fuzzy.
[n]Your fortune may be vague now.[f 1 1][e]
