[msg CrashWarning]
[f 0 5 -258][f 2 1][f 0 1 9]ATTENTION![n]
[f 0 1 0]Some players may experience a crash after
[n]the upcoming tutorial battle.
[n][n]We recommend saving the game now.[f 1 1][e]
[f 0 5 -258][f 2 1]If the game does crash, don't panic!
[n]Just launch P4G again and keep playing.
[n]The crash should not occur again for
[n]the rest of the game.[f 1 1][e]
[f 0 5 -258][f 2 1]We apologize for this bug and hope to
[n]fix it soon.
[n][n]-P4G CEP Team[f 1 1][e]